server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/movie_ticket
    username: movie_user
    password: moviepassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect